# fly.toml file generated for easy copying into your project

app = "tf-pocketbase-staging"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "./Dockerfile.staging"

[mounts]
  source = "pb_data_staging"  # Volume name
  destination = "/usr/local/bin/pb_data"   # Mount point in the app

[experimental]
  auto_rollback = true
  max_per_region = 1  # Important! Otherwise you risk data corruption...

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.http_options]
    h2_backend = true

  [http_service.concurrency]
    type = "connections"
    hard_limit = 550
    soft_limit = 500

[metrics]
  port = 9090
  path = "/metrics"
